name: MegaLinter

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: megalinter-${{ github.ref }}
  cancel-in-progress: true

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: MegaLinter
        id: ml
        uses: oxsecurity/megalinter@v8
        env:
          MEGALINTER_FLAVOR: all
          DISABLE_ERRORS: true
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
